# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieForm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'YouTubePlayer'

  # Pods for MovieForm

  target 'MovieFormTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieFormUITests' do
    # Pods for testing
  end

end
