# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NaverOAuthTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NaverOAuthTest

  pod 'naveridlogin-sdk-ios'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'GoogleSignIn'

  target 'NaverOAuthTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NaverOAuthTestUITests' do
    # Pods for testing
  end

end
