# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FloatActionButton' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FloatActionButton
  pod 'JJFloatingActionButton'

  target 'FloatActionButtonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FloatActionButtonUITests' do
    # Pods for testing
  end

end
