# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomView
  pod "PagingKit"

  target 'CustomViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CustomViewUITests' do
    # Pods for testing
  end

end
