# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BottomSheet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BottomSheet
  pod 'MaterialComponents/BottomSheet'
  pod 'PanModal' 

  target 'BottomSheetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BottomSheetUITests' do
    # Pods for testing
  end

end
